// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"maestro/internal/config"
	"maestro/internal/handler/server"
	"maestro/internal/infra/database/repository"
	"maestro/internal/platform/database"
	"maestro/internal/shared"
	"maestro/internal/usecase/task"
)

// Injectors from wire.go:

func InitializeServer() (*server.GRPCServer, error) {
	configConfig := config.LoadConfig()
	dsn := provideDSN(configConfig)
	db, err := database.NewPostgresDB(dsn)
	if err != nil {
		return nil, err
	}
	taskRepository := repository.NewPostgresTaskRepository(db)
	taskUsecase := taskusecase.NewTaskUsecase(taskRepository)
	port := providePort(configConfig)
	grpcServer := server.NewGRPCServer(taskUsecase, port)
	return grpcServer, nil
}

// wire.go:

// Tipos distintos para evitar conflito de bindings com string
type Port string

type DSN string

func providePort(cfg *config.Config) shared.Port {
	return shared.Port(":" + cfg.Port)
}

func provideDSN(cfg *config.Config) shared.DSN {
	return shared.DSN(cfg.DatabaseURL)
}
